### ISSUE TITLE
400 Bad Request importing iOS Device Restrictions

### ISSUE THREAD

**Issue by JelleMarc** [jseerden/IntuneBackupAndRestore#25]
When trying to import iOS Device Restrictions I get a 400 Bad Request error (error message below).
Work around is to open the file and remove the following part of the document located in "networkUsageRules" at the end of the document:

                              {
                                  "cellularDataBlockWhenRoaming":  false,
                                  "cellularDataBlocked":  false,
                                  "managedApps":  ""
                              },
                              {
                                  "cellularDataBlockWhenRoaming":  false,
                                  "cellularDataBlocked":  false,
                                  "managedApps":  ""
                              }

The error we get is as following:

Invoke-IntuneRestoreDeviceConfiguration : 400 Bad Request
{
  "error": {
    "code": "BadRequest",
    "message": "Property managedApps in payload has a value that does not match schema.",
    "innerError": {
      "date": "2021-02-15T13:16:04",
      "request-id": "6961121f-044d-4ef7-bbc8-414a5af8ab67",
      "client-request-id": "6961121f-044d-4ef7-bbc8-414a5af8ab67"
    }
  }
}
At C:\Program Files\WindowsPowerShell\Modules\IntuneBackupAndRestore\2.0.0\Public\Start-IntuneRestoreConfig.ps1:28
char:5
+     Invoke-IntuneRestoreDeviceConfiguration -Path $Path
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-IntuneRestoreDeviceConfiguratio
   n

**Comment by tehmichael** [comment]
The work around you posted works here.

**Comment by tehmichael** [comment]
Hey @JelleMarc, how did you go figuring out that the issue lied with the lines you removed above?

**Comment by JelleMarc** [comment]
Hi Michael,

I analysed the error and after that the code. I found out that the lines of code do not apply to any part in the policy I have created as far as I could see. It is unclear to me what this part is for and why the export would add it.

**Comment by tehmichael** [comment]
Oh, I see what you mean there - I missed that the error mentioned 'managedApps'.  I was running into another 400 Bad Request error in another issue here, so I was hoping to see how you troubleshot this issue.

**Comment by jseerden** [comment]
This issue should now be resolved in version 2.1.1.

iOS Device restrictions that are backed up with version 2.1.1 or higher can also be restored.

**Comment by JelleMarc** [comment]
Hi Jseerden,

After installing the newest version we are still receiving an error when importen the iOS Device Configuration file:


Invoke-IntuneRestoreDeviceCompliancePolicy : 400 Bad Request
{
  "error": {
    "code": "ModelValidationFailure",
    "message": "An entry with type 'microsoft.management.services.api.iosGeneralDeviceConfiguration' was found, but it
is not assignable to the expected type 'microsoft.management.services.api.deviceCompliancePolicy'. The type specified
in the entry must be equal to either the expected type or a derived type.",
    "innerError": {
      "message": "An entry with type 'microsoft.management.services.api.iosGeneralDeviceConfiguration' was found, but
it is not assignable to the expected type 'microsoft.management.services.api.deviceCompliancePolicy'. The type
specified in the entry must be equal to either the expected type or a derived type.",
      "date": "2021-02-22T13:07:28",
      "request-id": "9930a335-2ec1-4e0f-af3f-d467a9eed3cb",
      "client-request-id": "9930a335-2ec1-4e0f-af3f-d467a9eed3cb"
    }
  }
}
At C:\Program Files\WindowsPowerShell\Modules\IntuneBackupAndRestore\2.1.1\Public\Start-IntuneRestoreConfig.ps1:27
char:5
+     Invoke-IntuneRestoreDeviceCompliancePolicy -Path $Path
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-IntuneRestoreDeviceCompliancePo
   licy
